const menuButton=document.querySelector('.menu-toggle');
const mobileMenu=document.querySelector('.mobile-nav');
const toast=document.querySelector('.toast');let toastTimer;
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');mobileMenu.hidden=!open;});
mobileMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mobileMenu.hidden=true;menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Abrir menu');}));
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),4500);}
function legacyCopy(value){const field=document.createElement('textarea');field.value=value;field.style.cssText='position:fixed;left:0;top:0;width:1px;height:1px;opacity:0';document.body.append(field);field.focus();field.select();let ok=false;try{ok=document.execCommand('copy');}catch{}field.remove();return ok;}
function showCopyFallback(value){let dialog=document.querySelector('#copy-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='copy-dialog';dialog.className='copy-dialog';dialog.innerHTML='<form method="dialog"><h2>Endereço do servidor</h2><p>Selecione o endereço abaixo e copie para adicionar no Minecraft.</p><input aria-label="Endereço do servidor" readonly><button class="button primary" value="close">Fechar</button></form>';document.body.append(dialog);}dialog.querySelector('input').value=value;dialog.showModal();dialog.querySelector('input').select();}
document.querySelectorAll('.copy-ip').forEach(button=>button.addEventListener('click',async()=>{const value=button.dataset.copy;if(button.disabled)return;const original=button.innerHTML;button.disabled=true;button.textContent='Copiando…';let copied=false;if(navigator.clipboard?.writeText){try{await Promise.race([navigator.clipboard.writeText(value),new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),1500))]);copied=true;}catch{}}if(!copied)copied=legacyCopy(value);button.disabled=false;if(copied){button.textContent='Copiado ✓';showToast('Endereço do servidor copiado.');setTimeout(()=>{button.innerHTML=original;},2200);}else{button.innerHTML=original;showCopyFallback(value);}}));
const search=document.querySelector('#plugin-search');const filters=[...document.querySelectorAll('.filter')];const entries=[...document.querySelectorAll('.plugin-entry')];let category='Todos';
const normalize=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function filterGuide(){const query=normalize(search?.value||'');let count=0;entries.forEach(entry=>{const matches=(category==='Todos'||entry.dataset.category===category)&&normalize(entry.textContent).includes(query);entry.hidden=!matches;if(matches)count++;});const countLabel=document.querySelector('.results-count');if(countLabel)countLabel.textContent=count+' '+(count===1?'tópico':'tópicos');const empty=document.querySelector('.no-results');if(empty)empty.hidden=count>0;}
search?.addEventListener('input',filterGuide);filters.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;filters.forEach(item=>{const selected=item===button;item.classList.toggle('active',selected);item.setAttribute('aria-pressed',String(selected));});filterGuide();}));

document.querySelectorAll('.motion-toggle').forEach(button=>button.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');button.setAttribute('aria-pressed',String(paused));button.textContent=paused?'Animar fundo':'Pausar fundo';}));
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(items=>{items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('is-visible');observer.unobserve(item.target);}});},{threshold:.08});document.querySelectorAll('.intro-grid,.feature-rows article,.join-grid,.guide-callout>.shell').forEach(element=>{element.classList.add('reveal');observer.observe(element);});}

function openLinkedTopic(){if(!location.hash)return;const target=document.getElementById(location.hash.slice(1));if(target?.classList.contains('plugin-entry')){if(search)search.value='';category='Todos';filters.forEach(b=>{const active=b.dataset.filter==='Todos';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});filterGuide();target.open=true;target.scrollIntoView({block:'start'});}}window.addEventListener('hashchange',openLinkedTopic);openLinkedTopic();
