const menuButton=document.querySelector('.menu-toggle');
const mobileMenu=document.querySelector('.mobile-nav');
const toast=document.querySelector('.toast');let toastTimer;
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');mobileMenu.hidden=!open;});
mobileMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mobileMenu.hidden=true;menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Abrir menu');}));
document.querySelectorAll('.copy-ip').forEach(button=>button.addEventListener('click',async()=>{const value=button.dataset.copy;let copied=false;try{await navigator.clipboard.writeText(value);copied=true;}catch{const field=document.createElement('textarea');field.value=value;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();copied=document.execCommand('copy');field.remove();}toast.textContent=copied?'Endereço do servidor copiado.':'Copie o endereço: '+value;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),3500);}));
const search=document.querySelector('#plugin-search');const filters=[...document.querySelectorAll('.filter')];const entries=[...document.querySelectorAll('.plugin-entry')];let category='Todos';
const normalize=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function filterGuide(){const query=normalize(search?.value||'');let count=0;entries.forEach(entry=>{const matches=(category==='Todos'||entry.dataset.category===category)&&normalize(entry.textContent).includes(query);entry.hidden=!matches;if(matches)count++;});document.querySelector('.results-count').textContent=count+' '+(count===1?'tópico':'tópicos');document.querySelector('.no-results').hidden=count>0;}
search?.addEventListener('input',filterGuide);filters.forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;filters.forEach(item=>{const selected=item===button;item.classList.toggle('active',selected);item.setAttribute('aria-pressed',String(selected));});filterGuide();}));

document.querySelectorAll('.motion-toggle').forEach(button=>button.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');button.setAttribute('aria-pressed',String(paused));button.textContent=paused?'Animar fundo':'Pausar fundo';}));
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(items=>{items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('is-visible');observer.unobserve(item.target);}});},{threshold:.08});document.querySelectorAll('.intro-grid,.feature-rows article,.join-grid,.guide-callout>.shell').forEach(element=>{element.classList.add('reveal');observer.observe(element);});}
